#!/usr/bin/python
import sys

seps = sys.argv[1:]
print seps

lines = []
while True:
	try:
		line = raw_input()
		start = None
		for sep in seps:
			before, s, after = partition(line)
			if s:

			
		lines.append(raw_input())
	except EOFError:
		break

print lines
